apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warpnet-sre-challenge

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml

images:
  - name: theninjatuna/warpnet-sre-challenge
